export const followers = [
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Mr. Tiger', title: "I'm a big deal"},
];

export const followings = [
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
  {url: 'assets/tiger.jpg', username: 'Finn', title: "I'm a big deal"},
];